<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class BackendUser extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=[
    'activation_code'=>' ',
    'persist_code'=>' ',
    'reset_password_code'=>' ',
    'is_activated'=>0,
    'is_superuser'=>0
  ];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'first_name'=>'string',
    'last_name'=>'string',
    'login'=>'string',
    'email'=>'string',
    'password'=>'string',
    'activation_code'=>'string',
    'persist_code'=>'string',
    'reset_password_code'=>'string',
    'permissions'=>'string',
    'role_id'=>'integer',
    'is_activated'=>'integer',
    'is_superuser'=>'integer',
    'activated_at'=>'datetime',
    'last_login'=>'datetime',
    'created_at'=>'datetime',
    'updated_at'=>'datetime',
    'signature_id'=>'integer'
  ];
  public function role()
  {
    return $this->belongsTo('\App\Models\Role','role_id','id');
  }
  public function signature()
  {
    return $this->belongsTo('\App\Models\Signature','signature_id','id');
  }
  public function backendAccessLogs()
  {
    return $this->hasMany('\App\Models\Backend_access_log','backend_user_id','id');
  }
}
