<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class BackendAccessLog extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=[
    'ip_address'=>' ',
    'note'=>' '
  ];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'backend_user_id'=>'integer',
    'ip_address'=>'string',
    'note'=>'string',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
  public function backendUser()
  {
    return $this->belongsTo('\App\Models\Backend_user','backend_user_id','id');
  }
}
