<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Billing extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=[
    'billed'=>0,
    'paid'=>0,
    'sequence'=>0,
    'payment'=>0
  ];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'product_id'=>'integer',
    'bill_date'=>'datetime:Y-m-d',
    'bill_number'=>'integer',
    'bill_amount'=>'double',
    'billed'=>'integer',
    'paid'=>'integer',
    'paid_at'=>'datetime:Y-m-d',
    'sequence'=>'integer',
    'payment'=>'integer',
    'created_at'=>'datetime',
    'updated_at'=>'datetime',
    'payment_term_id'=>'integer'
  ];
  public function paymentTerm()
  {
    return $this->belongsTo('\App\Models\Payment_term','payment_term_id','id');
  }
  public function payments()
  {
    return $this->hasMany('\App\Models\Payment','billing_id','id');
  }
}
