<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Bounce extends Model
{
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'created_at'=>'datetime',
    'updated_at'=>'datetime',
    'email'=>'string',
    'bounce_date'=>'datetime:Y-m-d',
    'error_count'=>'integer',
    'code_error'=>'string',
    'eblast_id'=>'integer',
    'code_bounce_id'=>'integer'
  ];
  public function eblast()
  {
    return $this->belongsTo('\App\Models\Eblast','eblast_id','id');
  }
  public function codeBounce()
  {
    return $this->belongsTo('\App\Models\Code_bounce','code_bounce_id','id');
  }
}
