<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class BranchDashboard extends Model
{
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'branch_id'=>'integer',
    'user_total'=>'integer',
    'custom_list_total'=>'integer',
    'new_contract_today'=>'integer',
    'contract_total'=>'integer',
    'new_eblast_today'=>'integer',
    'eblast_total'=>'integer',
    'new_eblast_send_today'=>'integer',
    'eblast_send_total'=>'integer',
    'new_custom_contact_today'=>'integer',
    'custom_contact_total'=>'integer',
    'new_billing_today'=>'integer',
    'billing_total'=>'integer',
    'new_invoice_receive_today'=>'integer',
    'invoice_receive_this_month'=>'integer',
    'new_payment_send_today'=>'integer',
    'new_payment_send_this_month'=>'integer',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
  public function branch()
  {
    return $this->belongsTo('\App\Models\Branch','branch_id','id');
  }
}
