<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Branch extends Model
{
    protected $fillable = [
        'name',
        'company_id',
        'address',
        'province_id',
        'city',
        'postal_code',
        'active',
        'logo_file_en',
        'logo_file_fr'
    ];
  /**
  * The attributes that should be cast to native types.
  *
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'name'=>'string',
    'company_id'=>'integer',
    'address'=>'string',
    'province_id'=>'integer',
    'city'=>'string',
    'postal_code'=>'string',
    'created_at'=>'datetime',
    'updated_at'=>'datetime',
    'note'=>'string',
    'active'=>'integer',
    'website'=>'string',
    'logo_file_en'=>'string',
    'logo_file_fr'=>'string'
  ];
  public function company()
  {
    return $this->belongsTo('\App\Models\Company','company_id','id');
  }
  public function province()
  {
    return $this->belongsTo('\App\Models\Province','province_id','id');
  }
  public function branchDashboards()
  {
    return $this->hasMany('\App\Models\Branch_dashboard','branch_id','id');
  }
  public function libraries()
  {
    return $this->hasMany('\App\Models\Library','branch_id','id');
  }
  public function dashboardQps()
  {
    return $this->hasMany('\App\Models\Dashboard_qp','branch_id','id');
  }
  public function customLists()
  {
    return $this->belongsToMany('\App\Models\Custom_list','branch_has_custom_lists','branch_id','custom_list_id');
  }
  public function users()
  {
    return $this->belongsToMany('\App\Models\User','branch_has_users','branch_id','user_id');
  }
  public function contracts()
  {
    return $this->belongsToMany('\App\Models\Contract','contract_to_branches','branch_id','contract_id');
  }
}
