<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Relations\Pivot;

class BranchHasUser extends Pivot
{
    public $table = 'branch_has_users';
    protected $fillable = [
        'branch_id',
        'user_id'
    ];
  /**
  * Primary key name.
  *
  * @var string
  */
  public $primaryKey='branch_id';

  /**
  * Primary key is non-autoincrementing.
  *
  * @var bool
  */
  public $incrementing=false;

  /**
  * Do not automatically manage timestamps by Eloquent
  *
  * @var bool
  */
  public $timestamps=false;

  /**
  * The attributes that should be cast to native types.
  *
  * @var array
  */
  protected $casts=[
    'branch_id'=>'integer',
    'user_id'=>'integer'
  ];
}
