<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Click extends Model
{
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'eblast_id'=>'integer',
    'code'=>'string',
    'url'=>'string',
    'title'=>'string',
    'actions'=>'integer',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
  public function eblast()
  {
    return $this->belongsTo('\App\Models\Eblast','eblast_id','id');
  }
}
