<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = [
        'industry_id',
        'name',
        'address',
        'country_id',
        'province_id',
        'city',
        'postal_code',
        'active',
        'phone',
        'logo_file_en',
        'logo_file_fr'
    ];
  /**
  * The attributes that should be cast to native types.
  *
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'industry_id'=>'integer',
    'name'=>'string',
    'address'=>'string',
    'country_id'=>'integer',
    'province_id'=>'integer',
    'city'=>'string',
    'postal_code'=>'string',
    'note'=>'string',
    'active'=>'integer',
    'phone'=>'string',
    'website'=>'string',
    'media_folder'=>'string',
    'type_image'=>'string',
    'has_contract'=>'integer',
    'logo_file_en'=>'string',
    'logo_file_fr'=>'string',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
  public function province()
  {
    return $this->belongsTo('\App\Models\Province','province_id','id');
  }
  public function country()
  {
    return $this->belongsTo('\App\Models\Country','country_id','id');
  }
  public function industry()
  {
    return $this->belongsTo('\App\Models\Industry','industry_id','id');
  }
  public function branches()
  {
    return $this->hasMany('\App\Models\Branch','company_id','id');
  }
  public function companyDashboards()
  {
    return $this->hasMany('\App\Models\Company_dashboard','company_id','id');
  }
}
