<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Contract extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=[
    'amount'=>0,
    'renewed'=>0,
    'balance'=>0
  ];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'language'=>'string',
    'start_date'=>'datetime:Y-m-d',
    'end_date'=>'datetime:Y-m-d',
    'amount'=>'double',
    'shared'=>'integer',
    'renewed'=>'integer',
    'published'=>'integer',
    'balance'=>'integer',
    'comments'=>'string',
    'preferred_address'=>'integer',
    'payment_notes'=>'string',
    'term'=>'string',
    'sent'=>'integer',
    'sent_at'=>'datetime',
    'created_at'=>'datetime',
    'updated_at'=>'datetime',
    'payment_method_id'=>'integer',
    'seller_signature'=>'string',
    'client_signature'=>'string'
  ];
  public function paymentMethod()
  {
    return $this->belongsTo('\App\Models\Payment_method','payment_method_id','id');
  }
  public function eblasts()
  {
    return $this->hasMany('\App\Models\Eblast','contract_id','id');
  }
  public function paymentTerms()
  {
    return $this->hasMany('\App\Models\Payment_term','contract_id','id');
  }
  public function branches()
  {
    return $this->belongsToMany('\App\Models\Branch','contract_to_branches','contract_id','branch_id');
  }
  public function pricingLots()
  {
    return $this->belongsToMany('\App\Models\Pricing_lot','contract_to_pricing_lots','contract_id','pricing_lot_id');
  }
}
