<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=['is_active'=>1];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'name_en'=>'string',
    'name_fr'=>'string',
    'is_active'=>'integer',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
  public function companies()
  {
    return $this->hasMany('\App\Models\Company','country_id','id');
  }
  public function provinces()
  {
    return $this->hasMany('\App\Models\Province','country_id','id');
  }
}
