<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class CustomContact extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=[
    'elastic_mail'=>0,
    'active'=>0
  ];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'first_name'=>'string',
    'last_name'=>'string',
    'email'=>'string',
    'address'=>'string',
    'phone'=>'string',
    'title'=>'string',
    'company'=>'string',
    'public_key'=>'string',
    'elastic_mail'=>'integer',
    'active'=>'integer',
    'unsubscribe_at'=>'datetime',
    'created_at'=>'datetime',
    'updated_at'=>'datetime',
    'custom_list_id'=>'integer'
  ];
  public function customList()
  {
    return $this->belongsTo('\App\Models\Custom_list','custom_list_id','id');
  }
}
