<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class CustomList extends Model
{
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'name'=>'string',
    'created_at'=>'datetime',
    'updated_at'=>'datetime',
    'email'=>'string',
    'reminder'=>'string',
    'active'=>'integer',
    'views'=>'integer',
    'clicks'=>'integer',
    'price'=>'double',
    'by_unit'=>'double',
    'public_key'=>'string'
  ];
  public function customContacts()
  {
    return $this->hasMany('\App\Models\Custom_contact','custom_list_id','id');
  }
  public function branches()
  {
    return $this->belongsToMany('\App\Models\Branch','branch_has_custom_lists','custom_list_id','branch_id');
  }
}
