<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Eblast extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=['branch_id'=> ];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'created_at'=>'datetime',
    'updated_at'=>'datetime',
    'branch_id'=>'integer',
    'type_qp_id'=>'integer',
    'template_id'=>'integer',
    'pricing_lot_id'=>'integer',
    'status_id'=>'integer',
    'contract_id'=>'integer'
  ];
  public function typeQp()
  {
    return $this->belongsTo('\App\Models\Type_qp','type_qp_id','id');
  }
  public function template()
  {
    return $this->belongsTo('\App\Models\Template','template_id','id');
  }
  public function pricingLot()
  {
    return $this->belongsTo('\App\Models\Pricing_lot','pricing_lot_id','id');
  }
  public function status()
  {
    return $this->belongsTo('\App\Models\Status','status_id','id');
  }
  public function contract()
  {
    return $this->belongsTo('\App\Models\Contract','contract_id','id');
  }
  public function statisticQps()
  {
    return $this->hasMany('\App\Models\Statistic_qp','eblast_id','id');
  }
  public function bounces()
  {
    return $this->hasMany('\App\Models\Bounce','eblast_id','id');
  }
  public function eblastSends()
  {
    return $this->hasOne('\App\Models\Eblast_send','eblast_id','id');
  }
  public function eblastContents()
  {
    return $this->hasOne('\App\Models\Eblast_content','eblast_id','id');
  }
  public function clicks()
  {
    return $this->hasMany('\App\Models\Click','eblast_id','id');
  }
  public function eblastDetails()
  {
    return $this->hasOne('\App\Models\Eblast_detail','eblast_id','id');
  }
}
