<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class MerchantGateway extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=[
    'active'=>0,
    'live'=>0,
    'sandbox'=>0
  ];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'gateway'=>'string',
    'name_en'=>'string',
    'name_fr'=>'string',
    'created_at'=>'datetime',
    'updated_at'=>'datetime',
    'active'=>'integer',
    'account'=>'string',
    'client_id'=>'string',
    'key'=>'string',
    'secret'=>'string',
    'live'=>'integer',
    'sandbox'=>'integer',
    'note'=>'string'
  ];
}
