<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Metatable extends Model
{
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'table_name'=>'string',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
  public function permissions()
  {
    return $this->hasMany('\App\Models\Permission','metatable_id','id');
  }
}
