<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class PricingLot extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=['is_active'=>0];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'product_id'=>'integer',
    'name'=>'string',
    'min'=>'integer',
    'max'=>'integer',
    'price'=>'double',
    'available_term'=>'integer',
    'is_active'=>'integer',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
  public function product()
  {
    return $this->belongsTo('\App\Models\Product','product_id','id');
  }
  public function eblasts()
  {
    return $this->hasMany('\App\Models\Eblast','pricing_lot_id','id');
  }
  public function contracts()
  {
    return $this->belongsToMany('\App\Models\Contract','contract_to_pricing_lots','pricing_lot_id','contract_id');
  }
}
