<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=[
    'is_system'=>0,
    'is_active'=>1
  ];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'name_en'=>'string',
    'name_fr'=>'string',
    'description'=>'string',
    'is_system'=>'integer',
    'is_active'=>'integer',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
  public function users()
  {
    return $this->hasMany('\App\Models\User','role_id','id');
  }
  public function backendUsers()
  {
    return $this->hasMany('\App\Models\Backend_user','role_id','id');
  }
}
