<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Seo extends Model
{
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'page_title_en'=>'string',
    'page_title_fr'=>'string',
    'seo_title_en'=>'string',
    'seo_description_en'=>'string',
    'seo_description_fr'=>'string',
    'seo_keywords_en'=>'string',
    'seo_keywords_fr'=>'string',
    'seo_other_en'=>'string',
    'seo_other_fr'=>'string',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
}
