<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=['google_tag_manager_enable'=>0];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'site_name'=>'string',
    'site_slogan'=>'string',
    'site_logo'=>'string',
    'site_phone_primary'=>'string',
    'site_phone_secondary'=>'string',
    'country'=>'string',
    'currency_code'=>'string',
    'street_address'=>'string',
    'email_address'=>'string',
    'email_name'=>'string',
    'site_google_map'=>'string',
    'facebook_address'=>'string',
    'twitter_address'=>'string',
    'linkedin_plus_address'=>'string',
    'captcha_key'=>'string',
    'captcha_secret'=>'string',
    'google_analytic_tracking_id'=>'string',
    'google_tag_manager_id'=>'string',
    'google_tag_manager_enable'=>'integer',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
}
