<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Signature extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=['active'=>0];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'title'=>'string',
    'first_name'=>'string',
    'last_name'=>'string',
    'paraph'=>'string',
    'active'=>'integer',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
  public function users()
  {
    return $this->hasMany('\App\Models\User','signature_id','id');
  }
  public function backendUsers()
  {
    return $this->hasMany('\App\Models\Backend_user','signature_id','id');
  }
}
