<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'name'=>'string',
    'caption'=>'string',
    'link'=>'string',
    'target'=>'string',
    'language'=>'string',
    'sort'=>'integer',
    'map_id'=>'string',
    'map_code'=>'string',
    'published'=>'integer',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
}
