<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class StatisticQp extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=['click_total'=>0];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'eblast_id'=>'integer',
    'click_total'=>'integer',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
  public function eblast()
  {
    return $this->belongsTo('\App\Models\Eblast','eblast_id','id');
  }
}
