<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class SuperDashboard extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=['new_user_today'=>0];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'new_user_today'=>'integer',
    'new_company_today'=>'integer',
    'new_backend_user_today'=>'integer',
    'user_total'=>'integer',
    'company_total'=>'integer',
    'custom_list_total'=>'integer',
    'new_contract_today'=>'integer',
    'contract_total'=>'integer',
    'new_branch_today'=>'integer',
    'branch_total'=>'integer',
    'new_eblast_today'=>'integer',
    'eblast_total'=>'integer',
    'new_eblast_send_today'=>'integer',
    'eblast_send_total'=>'integer',
    'new_contact_today'=>'integer',
    'contact_total'=>'integer',
    'new_billing_today'=>'integer',
    'billing_total'=>'integer',
    'new_invoice_send_today'=>'integer',
    'invoice_send_this_month'=>'integer',
    'new_payment_receive_today'=>'integer',
    'new_payment_receive_this_month'=>'integer',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
}
