<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Template extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=['is_active'=>0];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'name'=>'string',
    'name_fr'=>'string',
    'email_file'=>'string',
    'partial_file'=>'string',
    'layout_elastic'=>'string',
    'layout'=>'string',
    'published'=>'integer',
    'admin'=>'datetime',
    'order'=>'integer',
    'is_active'=>'integer',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
  public function eblasts()
  {
    return $this->hasMany('\App\Models\Eblast','template_id','id');
  }
}
