<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class TotalDay extends Model
{
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'date_sent'=>'datetime:Y-m-d',
    'total_cost'=>'double',
    'en'=>'decimal',
    'total_en'=>'double',
    'fr'=>'decimal',
    'total_fr'=>'double',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
}
