<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class UserThrottle extends Model
{
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=[
    'attempt'=>0,
    'is_suspended'=>0,
    'is_banned'=>0
  ];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'user_id'=>'integer',
    'ip_address'=>'string',
    'attempt'=>'integer',
    'last_attempt_at'=>'datetime',
    'is_suspended'=>'integer',
    'suspended_at'=>'datetime',
    'is_banned'=>'integer',
    'banned_at'=>'datetime:H:i:s',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
  public function user()
  {
    return $this->belongsTo('\App\Models\User','user_id','id');
  }
}
