<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: 31682336-355d-4cf2-85ca-0f8ba155af8d */
/* Migration datetime: 2020-01-03 15:57:25.900130 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2020010315572590 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {
    Schema::create('user_throttles', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('user_id')->nullable(true)->unsigned();
      $table->string('ip_address',255)->nullable(true);
      $table->integer('attempt')->nullable(true)->default(0);
      $table->timestamp('last_attempt_at')->nullable(true);
      $table->tinyInteger('is_suspended')->nullable(true)->default(0);
      $table->timestamp('suspended_at')->nullable(true);
      $table->tinyInteger('is_banned')->nullable(true)->default(0);
      $table->time('banned_at')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('companies', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('industry_id')->nullable(true)->unsigned();
      $table->string('name',255)->nullable(true);
      $table->string('address',255)->nullable(true);
      $table->integer('country_id')->nullable(true)->unsigned();
      $table->integer('province_id')->nullable(true)->unsigned();
      $table->string('city',255)->nullable(true);
      $table->string('postal_code',15)->nullable(true);
      $table->text('note')->nullable(true);
      $table->tinyInteger('active')->nullable(true);
      $table->string('phone',155)->nullable(true);
      $table->string('website',155)->nullable(true);
      $table->string('media_folder',255)->nullable(true);
      $table->string('type_image',250)->nullable(true);
      $table->tinyInteger('has_contract')->nullable(true);
      $table->string('logo_file_en',255)->nullable(true);
      $table->string('logo_file_fr',255)->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('custom_lists', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('name',155)->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
      $table->string('email',155);
      $table->text('reminder')->nullable(true);
      $table->tinyInteger('active')->nullable(true);
      $table->integer('views')->nullable(true);
      $table->integer('clicks')->nullable(true);
      $table->double('price',10)->nullable(true);
      $table->double('by_unit',10)->nullable(true);
      $table->string('public_key',255)->nullable(true);
    });
    Schema::create('branches', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('name',255)->nullable(true);
      $table->integer('company_id')->nullable(true)->unsigned();
      $table->string('address',255)->nullable(true);
      $table->integer('province_id')->nullable(true)->unsigned();
      $table->string('city',255)->nullable(true);
      $table->string('postal_code',15)->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
      $table->text('note')->nullable(true);
      $table->tinyInteger('active')->nullable(true);
      $table->string('website',150)->nullable(true);
      $table->string('logo_file_en',250)->nullable(true);
      $table->string('logo_file_fr',250)->nullable(true);
    });
    Schema::create('industries', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('name_fr',155)->unique();
      $table->string('name_en',155)->unique();
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('custom_contacts', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('first_name',155)->nullable(true);
      $table->string('last_name',155)->nullable(true);
      $table->string('email',155)->nullable(true);
      $table->string('address',155)->nullable(true);
      $table->string('phone',38)->nullable(true);
      $table->string('title',155)->nullable(true);
      $table->string('company',155)->nullable(true);
      $table->string('public_key',155)->nullable(true);
      $table->integer('elastic_mail')->nullable(true)->default(0);
      $table->integer('active')->nullable(true)->default(0);
      $table->dateTime('unsubscribe_at')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
      $table->integer('custom_list_id')->nullable(true)->unsigned();
    });
    Schema::create('eblasts', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
      $table->integer('branch_id')->nullable(true)->default( );
      $table->integer('type_qp_id')->nullable(true)->unsigned();
      $table->integer('template_id')->nullable(true)->unsigned();
      $table->integer('pricing_lot_id')->nullable(true)->unsigned();
      $table->integer('status_id')->nullable(true)->unsigned();
      $table->integer('contract_id')->nullable(true);
    });
    Schema::create('statuses', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('name_en',150)->unique();
      $table->string('name_fr',150)->unique();
      $table->tinyInteger('is_active')->nullable(true)->default(0);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('type_qps', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('name_en',150)->unique();
      $table->string('name_fr',150)->unique();
      $table->timestamp('is_active')->nullable(true)->default('0');
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('branch_has_custom_lists', function (Blueprint $table) {
      $table->integer('branch_id')->unsigned();
      $table->integer('custom_list_id')->unsigned();
      $table->primary(['branch_id','custom_list_id']);
    });
    Schema::create('branch_has_users', function (Blueprint $table) {
      $table->integer('branch_id')->unsigned();
      $table->integer('user_id')->unsigned();
      $table->primary(['branch_id','user_id']);
    });
    Schema::create('user_has_permissions', function (Blueprint $table) {
      $table->integer('user_id')->unsigned();
      $table->integer('permission_id')->unsigned();
      $table->primary(['user_id','permission_id']);
    });
    Schema::create('branch_roles', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->tinyInteger('is_admin')->nullable(true)->default(0);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('user_has_branch_roles', function (Blueprint $table) {
      $table->integer('user_id')->unsigned();
      $table->integer('branch_role_id')->unsigned();
      $table->primary(['user_id','branch_role_id']);
    });
    Schema::create('company_dashboards', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('company_id')->nullable(true)->unsigned();
      $table->integer('user_total')->nullable(true);
      $table->integer('custom_list_total')->nullable(true);
      $table->integer('new_contract_today')->nullable(true);
      $table->integer('contract_total')->nullable(true);
      $table->integer('new_branch_today')->nullable(true);
      $table->integer('branch_total')->nullable(true);
      $table->integer('new_eblast_today')->nullable(true);
      $table->integer('eblast_total')->nullable(true);
      $table->integer('new_eblast_send_today')->nullable(true);
      $table->integer('eblast_send_total')->nullable(true);
      $table->integer('new_custom_contact_today')->nullable(true);
      $table->integer('custom_contact_total')->nullable(true);
      $table->integer('new_billing_today')->nullable(true);
      $table->integer('billing_total')->nullable(true);
      $table->integer('new_invoice_receive_today')->nullable(true);
      $table->integer('invoice_receive_this_month')->nullable(true);
      $table->integer('new_payment_send_today')->nullable(true);
      $table->integer('new_payment_send_this_month')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('branch_dashboards', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('branch_id')->nullable(true)->unsigned();
      $table->integer('user_total')->nullable(true);
      $table->integer('custom_list_total')->nullable(true);
      $table->integer('new_contract_today')->nullable(true);
      $table->integer('contract_total')->nullable(true);
      $table->integer('new_eblast_today')->nullable(true);
      $table->integer('eblast_total')->nullable(true);
      $table->integer('new_eblast_send_today')->nullable(true);
      $table->integer('eblast_send_total')->nullable(true);
      $table->integer('new_custom_contact_today')->nullable(true);
      $table->integer('custom_contact_total')->nullable(true);
      $table->integer('new_billing_today')->nullable(true);
      $table->integer('billing_total')->nullable(true);
      $table->integer('new_invoice_receive_today')->nullable(true);
      $table->integer('invoice_receive_this_month')->nullable(true);
      $table->integer('new_payment_send_today')->nullable(true);
      $table->integer('new_payment_send_this_month')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('contract_to_branches', function (Blueprint $table) {
      $table->integer('contract_id');
      $table->integer('branch_id')->unsigned();
      $table->primary(['contract_id','branch_id']);
    });
    Schema::create('roles', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('name_en',155)->unique();
      $table->string('name_fr',155)->unique();
      $table->text('description')->nullable(true);
      $table->tinyInteger('is_system')->nullable(true)->default(0);
      $table->tinyInteger('is_active')->nullable(true)->default(1);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('provinces', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('name_en',255)->nullable(true);
      $table->string('name_fr',255)->nullable(true);
      $table->integer('country_id')->nullable(true)->unsigned();
      $table->tinyInteger('is_active')->nullable(true)->default(1);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('users', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('username',155)->nullable(true)->unique();
      $table->string('first_name',155);
      $table->string('last_name',155);
      $table->string('email',155)->unique();
      $table->string('encoded_email',150)->nullable(true)->default(' ');
      $table->string('title',150)->nullable(true)->default(' ');
      $table->integer('province_id')->unsigned();
      $table->string('city',155)->nullable(true)->default(' ');
      $table->integer('role_id')->nullable(true)->default( )->unsigned();
      $table->string('language',25)->nullable(true)->default(' ');
      $table->string('phone',25)->nullable(true)->default(' ');
      $table->string('extension',10)->nullable(true)->default(' ');
      $table->string('mobile',20)->nullable(true)->default(' ');
      $table->string('street_addr',255)->nullable(true)->default(' ');
      $table->string('postal_code',15)->nullable(true)->default(' ');
      $table->string('password',150);
      $table->tinyInteger('is_activated')->nullable(true)->default(0);
      $table->string('remember_token',100)->nullable(true)->default(' ');
      $table->string('activation_code',255)->nullable(true)->default(' ');
      $table->string('persist_code',255)->nullable(true)->default(' ');
      $table->string('reset_password_code',255)->nullable(true)->default(' ');
      $table->text('permissions')->nullable(true);
      $table->tinyInteger('is_guest')->nullable(true)->default(1);
      $table->tinyInteger('is_superuser')->nullable(true)->default(0);
      $table->timestamp('last_seen')->nullable(true);
      $table->timestamp('activated_at')->nullable(true);
      $table->timestamp('last_login')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
      $table->timestamp('deleted_at')->nullable(true);
      $table->integer('signature_id')->nullable(true)->unsigned();
    });
    Schema::create('user_access_logs', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('user_id')->nullable(true)->unsigned();
      $table->string('ip_address',155)->nullable(true)->default(' ');
      $table->text('note')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('backend_users', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('first_name',255);
      $table->string('last_name',255);
      $table->string('login',155)->unique();
      $table->string('email',155)->unique();
      $table->string('password',255);
      $table->string('activation_code',255)->nullable(true)->default(' ');
      $table->string('persist_code',255)->nullable(true)->default(' ');
      $table->string('reset_password_code')->nullable(true)->default(' ');
      $table->string('permissions')->nullable(true);
      $table->integer('role_id')->nullable(true)->unsigned();
      $table->tinyInteger('is_activated')->nullable(true)->default(0);
      $table->tinyInteger('is_superuser')->nullable(true)->default(0);
      $table->timestamp('activated_at')->nullable(true);
      $table->timestamp('last_login')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
      $table->integer('signature_id')->nullable(true)->unsigned();
    });
    Schema::create('backend_access_logs', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('backend_user_id')->unsigned();
      $table->string('ip_address',155)->nullable(true)->default(' ');
      $table->string('note',255)->nullable(true)->default(' ');
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('settings', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('site_name',150);
      $table->string('site_slogan',150)->nullable(true);
      $table->string('site_logo',150)->nullable(true);
      $table->string('site_phone_primary',150)->nullable(true);
      $table->string('site_phone_secondary',150)->nullable(true);
      $table->string('country',150)->nullable(true);
      $table->string('currency_code',3)->nullable(true);
      $table->string('street_address',150)->nullable(true);
      $table->string('email_address',140)->nullable(true);
      $table->string('email_name',140)->nullable(true);
      $table->string('site_google_map',145)->nullable(true);
      $table->string('facebook_address',140)->nullable(true);
      $table->string('twitter_address',140)->nullable(true);
      $table->string('linkedin_plus_address',140)->nullable(true);
      $table->string('captcha_key',140)->nullable(true);
      $table->string('captcha_secret',140)->nullable(true);
      $table->string('google_analytic_tracking_id',140)->nullable(true);
      $table->string('google_tag_manager_id',140)->nullable(true);
      $table->tinyInteger('google_tag_manager_enable')->nullable(true)->default(0);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('countries', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('name_en',155)->unique();
      $table->string('name_fr',155)->unique();
      $table->tinyInteger('is_active')->nullable(true)->default(1);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('system_event_logs', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('level',255)->nullable(true);
      $table->text('message')->nullable(true);
      $table->mediumText('details')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('merchant_gateways', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('gateway',150)->nullable(true)->unique();
      $table->string('name_en',155)->nullable(true);
      $table->string('name_fr',150)->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
      $table->tinyInteger('active')->default(0);
      $table->string('account')->nullable(true);
      $table->string('client_id')->nullable(true);
      $table->string('key')->nullable(true);
      $table->string('secret')->nullable(true);
      $table->tinyInteger('live')->nullable(true)->default(0);
      $table->tinyInteger('sandbox')->nullable(true)->default(0);
      $table->string('note',1)->nullable(true);
    });
    Schema::create('seos', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('page_title_en',120)->nullable(true)->unique();
      $table->string('page_title_fr',120)->nullable(true)->unique();
      $table->string('seo_title_en',155)->nullable(true)->unique();
      $table->string('seo_description_en',155)->nullable(true)->unique();
      $table->string('seo_description_fr',155)->nullable(true)->unique();
      $table->string('seo_keywords_en',155)->nullable(true);
      $table->string('seo_keywords_fr',155)->nullable(true);
      $table->string('seo_other_en',155)->nullable(true);
      $table->string('seo_other_fr',150)->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('permissions', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('metatable_id')->nullable(true)->unsigned();
      $table->tinyInteger('read')->default(0);
      $table->tinyInteger('modify')->default(0);
      $table->tinyInteger('add')->nullable(true)->default(0);
      $table->tinyInteger('delete')->default(0);
      $table->tinyInteger('is_active')->nullable(true)->default(1);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('metatables', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('table_name')->unique();
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('super_dashboards', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('new_user_today')->nullable(true)->default(0);
      $table->integer('new_company_today')->nullable(true);
      $table->integer('new_backend_user_today')->nullable(true);
      $table->integer('user_total')->nullable(true);
      $table->integer('company_total')->nullable(true);
      $table->integer('custom_list_total')->nullable(true);
      $table->integer('new_contract_today')->nullable(true);
      $table->integer('contract_total')->nullable(true);
      $table->integer('new_branch_today')->nullable(true);
      $table->integer('branch_total')->nullable(true);
      $table->integer('new_eblast_today')->nullable(true);
      $table->integer('eblast_total')->nullable(true);
      $table->integer('new_eblast_send_today')->nullable(true);
      $table->integer('eblast_send_total')->nullable(true);
      $table->integer('new_contact_today')->nullable(true);
      $table->integer('contact_total')->nullable(true);
      $table->integer('new_billing_today')->nullable(true);
      $table->integer('billing_total')->nullable(true);
      $table->integer('new_invoice_send_today')->nullable(true);
      $table->integer('invoice_send_this_month')->nullable(true);
      $table->integer('new_payment_receive_today')->nullable(true);
      $table->integer('new_payment_receive_this_month')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('contract_statuses', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('taxes', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('name_en',155)->nullable(true);
      $table->string('name_fr',155)->nullable(true);
      $table->decimal('value',10)->nullable(true);
      $table->tinyInteger('is_active')->nullable(true)->default(0);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('transactions', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('user_id')->nullable(true);
      $table->tinyInteger('company_id');
      $table->tinyInteger('branch_id')->nullable(true);
      $table->string('company_name',150);
      $table->string('product_name',150)->nullable(true);
      $table->string('lot_name',150)->nullable(true);
      $table->decimal('mount',10)->nullable(true);
      $table->float('tps')->nullable(true);
      $table->float('tvq')->nullable(true);
      $table->float('total',8)->nullable(true);
      $table->string('gateway',50)->nullable(true);
      $table->text('description')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
      $table->integer('product_id')->nullable(true);
      $table->integer('pricing_lot_id')->nullable(true);
      $table->integer('billing_id')->nullable(true)->default(0);
      $table->integer('payment_id')->nullable(true);
      $table->integer('type_qp_id')->nullable(true);
    });
    Schema::create('statistic_qps', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('eblast_id')->nullable(true)->unsigned();
      $table->integer('click_total')->nullable(true)->default(0);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('sliders', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('name',155);
      $table->text('caption')->nullable(true);
      $table->string('link',255)->nullable(true);
      $table->string('target',60)->nullable(true);
      $table->string('language',15);
      $table->integer('sort')->nullable(true);
      $table->string('map_id',255)->nullable(true);
      $table->text('map_code')->nullable(true);
      $table->tinyInteger('published')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('bounces', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
      $table->string('email',155)->nullable(true);
      $table->date('bounce_date')->nullable(true);
      $table->tinyInteger('error_count');
      $table->string('code_error',150)->nullable(true);
      $table->integer('eblast_id')->nullable(true)->unsigned();
      $table->integer('code_bounce_id')->nullable(true)->unsigned();
    });
    Schema::create('code_bounces', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('type',255)->nullable(true);
      $table->string('description',255)->nullable(true);
      $table->tinyInteger('is_active')->nullable(true)->default(1);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('templates', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('name',155)->unique();
      $table->string('name_fr',155)->unique();
      $table->string('email_file')->nullable(true);
      $table->string('partial_file')->nullable(true);
      $table->string('layout_elastic')->nullable(true);
      $table->string('layout',155)->nullable(true);
      $table->tinyInteger('published')->nullable(true);
      $table->timestamp('admin')->nullable(true);
      $table->integer('order')->nullable(true);
      $table->tinyInteger('is_active')->nullable(true)->default(0);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('eblast_sends', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
      $table->integer('eblast_id')->nullable(true)->unique()->unsigned();
      $table->string('slug',255);
      $table->date('date_required')->nullable(true);
      $table->time('time_required')->nullable(true);
      $table->integer('status')->default(0);
      $table->dateTime('date_send')->nullable(true);
      $table->dateTime('date_elastic_send')->nullable(true);
      $table->dateTime('sent_final_at')->nullable(true);
      $table->dateTime('sent_final_elastic_at')->nullable(true);
      $table->tinyInteger('elastic')->nullable(true)->default(0);
      $table->tinyInteger('approved')->default(0);
      $table->tinyInteger('displayed')->default(0);
      $table->tinyInteger('server')->default(0);
      $table->integer('views')->default(0);
      $table->integer('recipients')->default(0);
      $table->integer('bounces_soft')->default(0);
      $table->integer('bounces_hard')->default(0);
      $table->integer('pages')->default(0);
      $table->integer('shared')->default(0);
      $table->integer('total_subs_normal')->default(0);
      $table->integer('total_subs_elastic')->default(0);
      $table->integer('outlook')->default(0);
      $table->tinyInteger('billed')->default(0);
      $table->string('ip_address',60)->nullable(true)->default('NULL');
      $table->tinyInteger('admin_fetch')->default(0);
      $table->decimal('unit_price',10)->default(0.00);
    });
    Schema::create('eblast_contents', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
      $table->integer('eblast_id')->unique()->unsigned();
      $table->integer('type_content_id')->unsigned();
      $table->string('filename_content',255);
      $table->string('source_path',255)->nullable(true);
      $table->string('mime',255)->nullable(true);
      $table->string('link_content',250)->nullable(true);
      $table->text('text_content')->nullable(true);
      $table->text('style_block')->nullable(true);
      $table->string('short_link',255)->nullable(true);
      $table->string('original_name',255);
      $table->integer('clicks');
      $table->string('block',255)->nullable(true);
      $table->tinyInteger('host_images');
      $table->tinyInteger('parsed_href');
      $table->string('code');
    });
    Schema::create('clicks', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('eblast_id')->nullable(true)->unsigned();
      $table->string('code',255);
      $table->string('url',255);
      $table->string('title',255)->nullable(true);
      $table->integer('actions');
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('libraries', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('branch_id')->nullable(true)->unsigned();
      $table->string('title',255);
      $table->string('source',255)->nullable(true);
      $table->integer('size')->nullable(true);
      $table->string('mime',255)->nullable(true);
      $table->string('public_key',255)->nullable(true);
      $table->tinyInteger('published')->default(0);
      $table->string('filename',255)->nullable(true)->default('NULL');
      $table->string('original_name',255)->nullable(true);
      $table->integer('height')->nullable(true);
      $table->integer('width')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('products', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('name_en',155)->unique();
      $table->string('name_fr',155)->unique();
      $table->tinyInteger('published')->nullable(true);
      $table->string('language',2)->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('contracts', function (Blueprint $table) {
      $table->integer('id')->autoIncrement();
      $table->string('language',2);
      $table->date('start_date')->nullable(true);
      $table->date('end_date')->nullable(true);
      $table->double('amount',10)->nullable(true)->default(0);
      $table->tinyInteger('shared')->nullable(true);
      $table->tinyInteger('renewed')->nullable(true)->default(0);
      $table->tinyInteger('published')->nullable(true);
      $table->integer('balance')->nullable(true)->default(0);
      $table->text('comments')->nullable(true);
      $table->tinyInteger('preferred_address')->nullable(true);
      $table->text('payment_notes')->nullable(true);
      $table->string('term')->nullable(true);
      $table->tinyInteger('sent')->nullable(true);
      $table->dateTime('sent_at')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
      $table->integer('payment_method_id')->nullable(true)->unsigned();
      $table->binary('seller_signature')->nullable(true);
      $table->binary('client_signature')->nullable(true);
    });
    Schema::create('type_contents', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('name',150)->unique();
      $table->tinyInteger('is_active')->nullable(true)->default(0);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('eblast_details', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('eblast_id')->unique()->unsigned();
      $table->string('title',150);
      $table->text('informations')->nullable(true);
      $table->text('notes')->nullable(true);
      $table->tinyInteger('period_show');
      $table->tinyInteger('show_qp_section')->default(0);
      $table->text('admin_notes')->nullable(true);
      $table->string('sender_name',255)->nullable(true);
      $table->double('total_cost',10)->nullable(true);
      $table->integer('total_qp');
      $table->tinyInteger('active')->default(0);
      $table->string('language',2)->nullable(true)->default(' ');
      $table->string('list_name',150)->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('total_days', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->date('date_sent')->nullable(true);
      $table->double('total_cost',19)->nullable(true);
      $table->decimal('en',23)->nullable(true);
      $table->double('total_en',19)->nullable(true);
      $table->decimal('fr',23)->nullable(true);
      $table->double('total_fr',19)->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('dashboard_qps', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('branch_id')->nullable(true)->unsigned();
      $table->dateTime('date_requested')->nullable(true);
      $table->string('slug',255)->nullable(true);
      $table->date('date_required')->nullable(true);
      $table->time('time_required')->nullable(true);
      $table->integer('status');
      $table->string('ip_address',150)->nullable(true);
      $table->tinyInteger('server')->nullable(true)->unsigned();
      $table->tinyInteger('approved')->nullable(true);
      $table->tinyInteger('displayed')->default(0);
      $table->tinyInteger('elastic')->default(0);
      $table->tinyInteger('admin_fetch')->default(0);
      $table->dateTime('date_send')->nullable(true);
      $table->dateTime('sent_final_at')->nullable(true);
      $table->dateTime('date_elastic_send')->nullable(true);
      $table->integer('views')->nullable(true);
      $table->integer('recipients')->nullable(true);
      $table->integer('total_subs_normal')->nullable(true);
      $table->integer('total_subs_elastic')->nullable(true);
      $table->integer('outlook')->nullable(true);
      $table->string('title',250)->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('billings', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('product_id')->nullable(true);
      $table->date('bill_date')->nullable(true);
      $table->integer('bill_number')->nullable(true);
      $table->double('bill_amount',10)->nullable(true);
      $table->tinyInteger('billed')->default(0);
      $table->tinyInteger('paid')->default(0);
      $table->date('paid_at')->nullable(true);
      $table->integer('sequence')->default(0);
      $table->integer('payment')->default(0);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
      $table->integer('payment_term_id')->nullable(true)->unsigned();
    });
    Schema::create('pricing_lots', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('product_id')->nullable(true)->unsigned();
      $table->string('name');
      $table->integer('min');
      $table->integer('max');
      $table->double('price',10);
      $table->integer('available_term')->nullable(true);
      $table->tinyInteger('is_active')->nullable(true)->default(0);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('payment_methods', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('name_en',155);
      $table->string('name_fr',155);
      $table->tinyInteger('is_active')->nullable(true)->default(0);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('payments', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('company_name',155)->nullable(true);
      $table->string('branch_name',155)->nullable(true);
      $table->decimal('amount',10)->nullable(true);
      $table->integer('branch_id')->nullable(true);
      $table->integer('user_id')->nullable(true);
      $table->integer('company_id')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
      $table->integer('billing_id')->nullable(true)->unsigned();
    });
    Schema::create('signatures', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->string('title')->nullable(true);
      $table->string('first_name',155)->nullable(true);
      $table->string('last_name',155)->nullable(true);
      $table->binary('paraph')->nullable(true);
      $table->tinyInteger('active')->nullable(true)->default(0);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('contract_to_pricing_lots', function (Blueprint $table) {
      $table->integer('contract_id');
      $table->integer('pricing_lot_id')->unsigned();
      $table->primary(['contract_id','pricing_lot_id']);
    });
    Schema::create('payment_terms', function (Blueprint $table) {
      $table->integer('id')->autoIncrement()->unsigned();
      $table->integer('contract_id')->nullable(true);
      $table->double('amount',10)->nullable(true);
      $table->date('due_date')->nullable(true);
      $table->tinyInteger('is_invoice_send')->nullable(true)->default(0);
      $table->tinyInteger('is_paid')->nullable(true)->default(0);
      $table->tinyInteger('is_active')->nullable(true)->default(1);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::table('user_throttles', function (Blueprint $table) {
      $table->foreign('user_id')->references('id')->on('users');
    });
    Schema::table('companies', function (Blueprint $table) {
      $table->foreign('province_id')->references('id')->on('provinces');
    });
    Schema::table('companies', function (Blueprint $table) {
      $table->foreign('country_id')->references('id')->on('countries');
    });
    Schema::table('companies', function (Blueprint $table) {
      $table->foreign('industry_id')->references('id')->on('industries');
    });
    Schema::table('branches', function (Blueprint $table) {
      $table->foreign('company_id')->references('id')->on('companies');
    });
    Schema::table('branches', function (Blueprint $table) {
      $table->foreign('province_id')->references('id')->on('provinces');
    });
    Schema::table('custom_contacts', function (Blueprint $table) {
      $table->foreign('custom_list_id')->references('id')->on('custom_lists');
    });
    Schema::table('eblasts', function (Blueprint $table) {
      $table->foreign('type_qp_id')->references('id')->on('type_qps');
    });
    Schema::table('eblasts', function (Blueprint $table) {
      $table->foreign('template_id')->references('id')->on('templates');
    });
    Schema::table('eblasts', function (Blueprint $table) {
      $table->foreign('pricing_lot_id')->references('id')->on('pricing_lots');
    });
    Schema::table('eblasts', function (Blueprint $table) {
      $table->foreign('status_id')->references('id')->on('statuses');
    });
    Schema::table('eblasts', function (Blueprint $table) {
      $table->foreign('contract_id')->references('id')->on('contracts');
    });
    Schema::table('company_dashboards', function (Blueprint $table) {
      $table->foreign('company_id')->references('id')->on('companies');
    });
    Schema::table('branch_dashboards', function (Blueprint $table) {
      $table->foreign('branch_id')->references('id')->on('branches');
    });
    Schema::table('provinces', function (Blueprint $table) {
      $table->foreign('country_id')->references('id')->on('countries');
    });
    Schema::table('users', function (Blueprint $table) {
      $table->foreign('role_id')->references('id')->on('roles');
    });
    Schema::table('users', function (Blueprint $table) {
      $table->foreign('province_id')->references('id')->on('provinces');
    });
    Schema::table('users', function (Blueprint $table) {
      $table->foreign('signature_id')->references('id')->on('signatures');
    });
    Schema::table('user_access_logs', function (Blueprint $table) {
      $table->foreign('user_id')->references('id')->on('users');
    });
    Schema::table('backend_users', function (Blueprint $table) {
      $table->foreign('role_id')->references('id')->on('roles');
    });
    Schema::table('backend_users', function (Blueprint $table) {
      $table->foreign('signature_id')->references('id')->on('signatures');
    });
    Schema::table('backend_access_logs', function (Blueprint $table) {
      $table->foreign('backend_user_id')->references('id')->on('backend_users');
    });
    Schema::table('permissions', function (Blueprint $table) {
      $table->foreign('metatable_id')->references('id')->on('metatables');
    });
    Schema::table('statistic_qps', function (Blueprint $table) {
      $table->foreign('eblast_id')->references('id')->on('eblasts');
    });
    Schema::table('bounces', function (Blueprint $table) {
      $table->foreign('eblast_id')->references('id')->on('eblasts');
    });
    Schema::table('bounces', function (Blueprint $table) {
      $table->foreign('code_bounce_id')->references('id')->on('code_bounces');
    });
    Schema::table('eblast_sends', function (Blueprint $table) {
      $table->foreign('eblast_id')->references('id')->on('eblasts');
    });
    Schema::table('eblast_contents', function (Blueprint $table) {
      $table->foreign('eblast_id')->references('id')->on('eblasts');
    });
    Schema::table('eblast_contents', function (Blueprint $table) {
      $table->foreign('type_content_id')->references('id')->on('type_contents');
    });
    Schema::table('clicks', function (Blueprint $table) {
      $table->foreign('eblast_id')->references('id')->on('eblasts');
    });
    Schema::table('libraries', function (Blueprint $table) {
      $table->foreign('branch_id')->references('id')->on('branches');
    });
    Schema::table('contracts', function (Blueprint $table) {
      $table->foreign('payment_method_id')->references('id')->on('payment_methods');
    });
    Schema::table('eblast_details', function (Blueprint $table) {
      $table->foreign('eblast_id')->references('id')->on('eblasts');
    });
    Schema::table('dashboard_qps', function (Blueprint $table) {
      $table->foreign('branch_id')->references('id')->on('branches');
    });
    Schema::table('billings', function (Blueprint $table) {
      $table->foreign('payment_term_id')->references('id')->on('payment_terms');
    });
    Schema::table('pricing_lots', function (Blueprint $table) {
      $table->foreign('product_id')->references('id')->on('products');
    });
    Schema::table('payments', function (Blueprint $table) {
      $table->foreign('billing_id')->references('id')->on('billings');
    });
    Schema::table('payment_terms', function (Blueprint $table) {
      $table->foreign('contract_id')->references('id')->on('contracts');
    });
    Schema::table('branch_has_custom_lists', function (Blueprint $table) {
      $table->foreign('custom_list_id')->references('id')->on('custom_lists');
      $table->foreign('branch_id')->references('id')->on('branches');
    });
    Schema::table('branch_has_users', function (Blueprint $table) {
      $table->foreign('user_id')->references('id')->on('users');
      $table->foreign('branch_id')->references('id')->on('branches');
    });
    Schema::table('user_has_permissions', function (Blueprint $table) {
      $table->foreign('permission_id')->references('id')->on('permissions');
      $table->foreign('user_id')->references('id')->on('users');
    });
    Schema::table('user_has_branch_roles', function (Blueprint $table) {
      $table->foreign('branch_role_id')->references('id')->on('branch_roles');
      $table->foreign('user_id')->references('id')->on('users');
    });
    Schema::table('contract_to_branches', function (Blueprint $table) {
      $table->foreign('branch_id')->references('id')->on('branches');
      $table->foreign('contract_id')->references('id')->on('contracts');
    });
    Schema::table('contract_to_pricing_lots', function (Blueprint $table) {
      $table->foreign('pricing_lot_id')->references('id')->on('pricing_lots');
      $table->foreign('contract_id')->references('id')->on('contracts');
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('contract_to_pricing_lots', function (Blueprint $table) {
      $table->dropForeign('pricing_lot_id');
      $table->dropForeign('contract_id');
    });
    Schema::table('contract_to_branches', function (Blueprint $table) {
      $table->dropForeign('branch_id');
      $table->dropForeign('contract_id');
    });
    Schema::table('user_has_branch_roles', function (Blueprint $table) {
      $table->dropForeign('branch_role_id');
      $table->dropForeign('user_id');
    });
    Schema::table('user_has_permissions', function (Blueprint $table) {
      $table->dropForeign('permission_id');
      $table->dropForeign('user_id');
    });
    Schema::table('branch_has_users', function (Blueprint $table) {
      $table->dropForeign('user_id');
      $table->dropForeign('branch_id');
    });
    Schema::table('branch_has_custom_lists', function (Blueprint $table) {
      $table->dropForeign('custom_list_id');
      $table->dropForeign('branch_id');
    });
    Schema::table('payment_terms', function (Blueprint $table) {
      $table->dropForeign(['contract_id']);
    });
    Schema::table('payments', function (Blueprint $table) {
      $table->dropForeign(['billing_id']);
    });
    Schema::table('pricing_lots', function (Blueprint $table) {
      $table->dropForeign(['product_id']);
    });
    Schema::table('billings', function (Blueprint $table) {
      $table->dropForeign(['payment_term_id']);
    });
    Schema::table('dashboard_qps', function (Blueprint $table) {
      $table->dropForeign(['branch_id']);
    });
    Schema::table('eblast_details', function (Blueprint $table) {
      $table->dropForeign(['eblast_id']);
    });
    Schema::table('contracts', function (Blueprint $table) {
      $table->dropForeign(['payment_method_id']);
    });
    Schema::table('libraries', function (Blueprint $table) {
      $table->dropForeign(['branch_id']);
    });
    Schema::table('clicks', function (Blueprint $table) {
      $table->dropForeign(['eblast_id']);
    });
    Schema::table('eblast_contents', function (Blueprint $table) {
      $table->dropForeign(['type_content_id']);
    });
    Schema::table('eblast_contents', function (Blueprint $table) {
      $table->dropForeign(['eblast_id']);
    });
    Schema::table('eblast_sends', function (Blueprint $table) {
      $table->dropForeign(['eblast_id']);
    });
    Schema::table('bounces', function (Blueprint $table) {
      $table->dropForeign(['code_bounce_id']);
    });
    Schema::table('bounces', function (Blueprint $table) {
      $table->dropForeign(['eblast_id']);
    });
    Schema::table('statistic_qps', function (Blueprint $table) {
      $table->dropForeign(['eblast_id']);
    });
    Schema::table('permissions', function (Blueprint $table) {
      $table->dropForeign(['metatable_id']);
    });
    Schema::table('backend_access_logs', function (Blueprint $table) {
      $table->dropForeign(['backend_user_id']);
    });
    Schema::table('backend_users', function (Blueprint $table) {
      $table->dropForeign(['signature_id']);
    });
    Schema::table('backend_users', function (Blueprint $table) {
      $table->dropForeign(['role_id']);
    });
    Schema::table('user_access_logs', function (Blueprint $table) {
      $table->dropForeign(['user_id']);
    });
    Schema::table('users', function (Blueprint $table) {
      $table->dropForeign(['signature_id']);
    });
    Schema::table('users', function (Blueprint $table) {
      $table->dropForeign(['province_id']);
    });
    Schema::table('users', function (Blueprint $table) {
      $table->dropForeign(['role_id']);
    });
    Schema::table('provinces', function (Blueprint $table) {
      $table->dropForeign(['country_id']);
    });
    Schema::table('branch_dashboards', function (Blueprint $table) {
      $table->dropForeign(['branch_id']);
    });
    Schema::table('company_dashboards', function (Blueprint $table) {
      $table->dropForeign(['company_id']);
    });
    Schema::table('eblasts', function (Blueprint $table) {
      $table->dropForeign(['contract_id']);
    });
    Schema::table('eblasts', function (Blueprint $table) {
      $table->dropForeign(['status_id']);
    });
    Schema::table('eblasts', function (Blueprint $table) {
      $table->dropForeign(['pricing_lot_id']);
    });
    Schema::table('eblasts', function (Blueprint $table) {
      $table->dropForeign(['template_id']);
    });
    Schema::table('eblasts', function (Blueprint $table) {
      $table->dropForeign(['type_qp_id']);
    });
    Schema::table('custom_contacts', function (Blueprint $table) {
      $table->dropForeign(['custom_list_id']);
    });
    Schema::table('branches', function (Blueprint $table) {
      $table->dropForeign(['province_id']);
    });
    Schema::table('branches', function (Blueprint $table) {
      $table->dropForeign(['company_id']);
    });
    Schema::table('companies', function (Blueprint $table) {
      $table->dropForeign(['industry_id']);
    });
    Schema::table('companies', function (Blueprint $table) {
      $table->dropForeign(['country_id']);
    });
    Schema::table('companies', function (Blueprint $table) {
      $table->dropForeign(['province_id']);
    });
    Schema::table('user_throttles', function (Blueprint $table) {
      $table->dropForeign(['user_id']);
    });
    Schema::dropIfExists('payment_terms');
    Schema::dropIfExists('contract_to_pricing_lots');
    Schema::dropIfExists('signatures');
    Schema::dropIfExists('payments');
    Schema::dropIfExists('payment_methods');
    Schema::dropIfExists('pricing_lots');
    Schema::dropIfExists('billings');
    Schema::dropIfExists('dashboard_qps');
    Schema::dropIfExists('total_days');
    Schema::dropIfExists('eblast_details');
    Schema::dropIfExists('type_contents');
    Schema::dropIfExists('contracts');
    Schema::dropIfExists('products');
    Schema::dropIfExists('libraries');
    Schema::dropIfExists('clicks');
    Schema::dropIfExists('eblast_contents');
    Schema::dropIfExists('eblast_sends');
    Schema::dropIfExists('templates');
    Schema::dropIfExists('code_bounces');
    Schema::dropIfExists('bounces');
    Schema::dropIfExists('sliders');
    Schema::dropIfExists('statistic_qps');
    Schema::dropIfExists('transactions');
    Schema::dropIfExists('taxes');
    Schema::dropIfExists('contract_statuses');
    Schema::dropIfExists('super_dashboards');
    Schema::dropIfExists('metatables');
    Schema::dropIfExists('permissions');
    Schema::dropIfExists('seos');
    Schema::dropIfExists('merchant_gateways');
    Schema::dropIfExists('system_event_logs');
    Schema::dropIfExists('countries');
    Schema::dropIfExists('settings');
    Schema::dropIfExists('backend_access_logs');
    Schema::dropIfExists('backend_users');
    Schema::dropIfExists('user_access_logs');
    Schema::dropIfExists('users');
    Schema::dropIfExists('provinces');
    Schema::dropIfExists('roles');
    Schema::dropIfExists('contract_to_branches');
    Schema::dropIfExists('branch_dashboards');
    Schema::dropIfExists('company_dashboards');
    Schema::dropIfExists('user_has_branch_roles');
    Schema::dropIfExists('branch_roles');
    Schema::dropIfExists('user_has_permissions');
    Schema::dropIfExists('branch_has_users');
    Schema::dropIfExists('branch_has_custom_lists');
    Schema::dropIfExists('type_qps');
    Schema::dropIfExists('statuses');
    Schema::dropIfExists('eblasts');
    Schema::dropIfExists('custom_contacts');
    Schema::dropIfExists('industries');
    Schema::dropIfExists('branches');
    Schema::dropIfExists('custom_lists');
    Schema::dropIfExists('companies');
    Schema::dropIfExists('user_throttles');
  }
}
